- hosts: application
  remote_user: ubuntu
  become: yes
  tasks:

    - name: Update apt
      apt:
        update_cache: yes
    

    - name: Create directory
      file:
        name: jenkins_home
        state: directory
        mode: 0777


    - name: Install openjdk
      apt:
        name: openjdk-8-jdk
        state: present


    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present


    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present


    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes


    - name: Install docker-compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: '+x'


    - name: Ensure Docker is running
      service: 
        name: docker 
        state: started



